{
	"version": 1739190264,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/hat-sheet0.png",
		"images/jaden-sheet0.png",
		"images/bg-sheet0.png",
		"images/anchor-sheet0.png",
		"images/sprite3sheet-sheet0.png",
		"images/jadensmithwithhouse-sheet0.png",
		"images/sprite-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/house drop.m4a",
		"media/house drop.ogg",
		"media/boing.m4a",
		"media/boing.ogg",
		"media/bg (1).m4a",
		"media/bg (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}